### ISSUE TITLE
waterbased mobs spawn depsite protection

### ISSUE THREAD

**Issue by Bastrabun** [berengma/water_life#81]
A player of mine has a swimming pool in a savanna biome, in a protected area of his. He often gets snakes spawned in there.

Please make them respect protections

**Comment by berengma** [comment]
I will think about it.

**Comment by berengma** [comment]
I do not want to generally forbid them to spawn in protected areas. Maybe you have an other idea ? Like something which could be crafted and placed to scare them away ?

**Comment by Gundul42** [comment]
No idea ? Can be closed I guess.

**Comment by berengma** [comment]
I checked code and Snakes should not spawn in protected areas.
Was that really protected ? And by which protection mod ?

**Comment by fluxionary** [comment]
The protection mod is "areas". I solved @Bastrabun's issue by altering our fork to properly check for protection, but this change got wiped when we merged in recent updates, and snakes, crocs, etc. are again spawning in protected areas. 

Note that this is really only an issue w/ *hostile* mobs. No other mod we use spawns monsters in players' houses. 

My previous fix was a bit hacky, which was why I never submitted it. If/when I get around to fixing it again, I'll submit what I do. I remember the code needed a whole lot of TLC in general, though.

**Comment by berengma** [comment]
Spawning happens in the spawn function only. So whatever is not meant to be spawned, just add a is_protected check right before the final entity is spawned in the game. That is pretty easy because you just have to search for "snake" in spawn.lua and then add the if minetest.is_protected(pos) then [...] end. 
I remember like I had a global flag for not spawning in protected areas, maybe not for snakes though, to make it more realistic, I do not remember anymore :)
