### ISSUE TITLE
Renewable seagrasses/kelp

### ISSUE THREAD

**Issue by BlueTangsRock** [berengma/water_life#94]
Greetings! In Waterlife mod, the corals are currently renewable, via artificial reef blocks, however it would be great if the different types of seagrasses and kelp could have a method of renewability as well. Especially since there's the seagrass salad food item, seagrass farms could be made to obtain more ingredients. Perhaps, when mined, the player could aquire 1-4 seagrass/kelp items (of the same color variant) from a single plant? This would help avoid the need for ABM spreading mechanics.

**Comment by berengma** [comment]
Hello, yes why not. Sounds like a good idea. I am still waiting for a Dugong model and animation for the kelp and seagrass forests

**Comment by berengma** [comment]
@BlueTangsRock try the dev branch, kelps now spread and they give more drops depending on their length

**Comment by BlueTangsRock** [comment]
That's great! Perhaps, instead of artificial coral skeleton nodes spreading kelp/seagrass it could be "Seagrass turf/meadow" nodes (possibly crafted with sand and any type of seagrass)? I could create and upload a quick texture for it tomorrow if interested.

**Comment by berengma** [comment]
Thanks for the offer. While that is a good idea because it is more realistic, I must say from my experience on my servers that players usually get confused by having too many nodes doing the same thing actually. That is why I would say we'd better stick to the artificial coral skeleton. So one for all is keeping it easy for everyone.

**Comment by BlueTangsRock** [comment]
No problem, that's understandable.
